[theme]
primaryColor = "#3d5158"         # Color dorado para botones y detalles
backgroundColor = "#2974caad"      # Fondo oscuro elegante (puedes cambiarlo a un tono claro si prefieres)
secondaryBackgroundColor = "#4c702e" # Fondo de las cajas de búsqueda
textColor = "#01010e"            # Letras de color blanco hueso muy legibles
font = "sans serif"                 # Tipo de letra elegante estilo libro

